export const ACTION_TYPE_GO_TO_NEXT_MONTH = 'GO_TO_NEXT_MONTH';
export const ACTION_TYPE_GO_TO_PREV_MONTH = 'GO_TO_PREV_MONTH';
export const ACTION_TYPE_GO_TO_NEXT_YEAR  = 'GO_TO_NEXT_YEAR';
export const ACTION_TYPE_GO_TO_PREV_YEAR  = 'GO_TO_PREV_YEAR';